<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'WapplerSystems\\WsFlexslider\\Controller\\FlexsliderController' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/Controller/FlexsliderController.php',
    'WapplerSystems\\WsFlexslider\\Domain\\Model\\Content' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/Domain/Model/Content.php',
    'WapplerSystems\\WsFlexslider\\Domain\\Model\\Image' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/Domain/Model/Image.php',
    'WapplerSystems\\WsFlexslider\\Domain\\Repository\\ContentRepository' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/Domain/Repository/ContentRepository.php',
    'WapplerSystems\\WsFlexslider\\Domain\\Repository\\ImageRepository' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/Domain/Repository/ImageRepository.php',
    'WapplerSystems\\WsFlexslider\\Hooks\\ItemsProcFunc' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/Hooks/ItemsProcFunc.php',
    'WapplerSystems\\WsFlexslider\\Utility\\Div' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/Utility/Div.php',
    'WapplerSystems\\WsFlexslider\\Utility\\TemplateLayout' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/Utility/TemplateLayout.php',
    'WapplerSystems\\WsFlexslider\\ViewHelpers\\PageRenderer\\AddJsFooterInlineCodeViewHelper' => $typo3InstallDir . 'typo3conf/ext/ws_flexslider/Classes/ViewHelpers/PageRenderer/AddJsFooterInlineCodeViewHelper.php',
);
